name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      # The image is not pushed anywhere at the moment but serves the following purposes:
      # (a) performs the npm run build when building the image, and
      # (b) acts as a placeholder if we want to deploy as a container in the future.
      - name: Build the image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          platforms: linux/amd64
          push: false
          build-args: |
            HEAD_COMMIT_HASH=${{ github.sha }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/bettergov:${{github.sha}}
            ghcr.io/${{ github.repository_owner }}/bettergov:latest

  lint_checks:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npx prettier --check .
